### ISSUE TITLE
Unit properties which should return char or bool always throw InvalidOperationException

### ISSUE THREAD

**Issue by YakaryBovine** [Drake53/War3Api#14]
If I try to read Warcraft 3 object data generated using World Editor updated to 1.32, then try to read any property which returns either char or bool, an InvalidOperationException is thrown.

**Comment by Drake53** [comment]
It seems that even though the bool and char types are defined in the .w3o format, the int and string types respectively are used instead. This is not only an issue with the property getters (which throw) but also the setters, because the world editor does not recognize the modifications if they have the wrong type.

**Comment by Drake53** [comment]
Fix: https://github.com/Drake53/War3Api/commit/c0a342bef522ffab0a1662c9f1ba76009ee91659

I only tested it for unit's hotkey and campaign classification properties, but I assume this applies to all bool/char properties.

**Comment by YakaryBovine** [comment]
Fantastic, thank you. This would also explain why I'd been unable to set hotkeys correctly. I am now able to coherently read all fields in my object data, which should cover every field.
