### ISSUE TITLE
War3Api.Object.Generator does not generate fields with percentage values

### ISSUE THREAD

**Issue by YakaryBovine** [Drake53/War3Api#17]
For example, the following are missing:
**CloudOfFog:** DataChanceToMiss
**Defend:** DataDamageTaken, DataDamageDealt
**InnerFire:** DataDamageIncrease

However, the following is present:
**DemonHunterEvasion:** DataChanceToEvade

So I'm not completely certain what the rule is. This issue is new as of the latest commits.

Please let me know if this kind of feedback isn't helpful - I realize you may already be aware of the problem with a commit in the works.

**Comment by Drake53** [comment]
Thanks for the feedback, wasn't aware of this but I know what causes it.

When the display name of an identifier contains '%' I'm using the data name instead (this is the column name in the .slk file).
As a result the identifier becomes something like DataData_<code>.

Reason I was doing this is because sometimes the identifier contains "%s", which is like "{0}" in C# to format a string.
